default: &default
  adapter: postgresql
  encoding: utf8
  host: 127.0.0.1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: social_network_development
  username: nataly
  password: 12345678

test:
  <<: *default
  database: social_network_test
  username: nataly
  password: 12345678
